/**
 * @file BqRegsiters.h
 * @brief BQ76940 register addresses and bit definitions.
 */

#ifndef BQREGISTERS_H
#define BQREGISTERS_H

//  IC Address
#define IC_ADDRESS 0x08

//  Register Address
#define REGISTER_SYS_STAT_ADDRESS  0x00
#define REGISTER_CELLBAL1_ADDRESS  0x01
#define REGISTER_CELLBAL2_ADDRESS  0x02
#define REGISTER_CELLBAL3_ADDRESS  0x03
#define REGISTER_SYS_CTRL1_ADDRESS  0x04
#define REGISTER_SYS_CTRL2_ADDRESS  0x05
#define REGISTER_PROTECT1_ADDRESS  0x06
#define REGISTER_PROTECT2_ADDRESS  0x07
#define REGISTER_PROTECT3_ADDRESS  0x08
#define REGISTER_OV_TRIP_ADDRESS  0x09
#define REGISTER_UV_TRIP_ADDRESS  0x0A
#define REGISTER_CC_CFG_ADDRESS  0x0B
#define REGISTER_VC1_HI_ADDRESS  0x0C
#define REGISTER_VC1_LO_ADDRESS  0x0D
#define REGISTER_VC2_HI_ADDRESS  0x0E
#define REGISTER_VC2_LO_ADDRESS  0x0F
#define REGISTER_VC3_HI_ADDRESS  0x10
#define REGISTER_VC3_LO_ADDRESS  0x11
#define REGISTER_VC4_HI_ADDRESS  0x12
#define REGISTER_VC4_LO_ADDRESS  0x13
#define REGISTER_VC5_HI_ADDRESS  0x14
#define REGISTER_VC5_LO_ADDRESS  0x15
#define REGISTER_VC6_HI_ADDRESS  0x16
#define REGISTER_VC6_LO_ADDRESS  0x17
#define REGISTER_VC7_HI_ADDRESS  0x18
#define REGISTER_VC7_LO_ADDRESS  0x19
#define REGISTER_VC8_HI_ADDRESS  0x1A
#define REGISTER_VC8_LO_ADDRESS  0x1B
#define REGISTER_VC9_HI_ADDRESS  0x1C
#define REGISTER_VC9_LO_ADDRESS  0x1D
#define REGISTER_VC10_HI_ADDRESS  0x1E
#define REGISTER_VC10_LO_ADDRESS  0x1F
#define REGISTER_VC11_HI_ADDRESS  0x20
#define REGISTER_VC11_LO_ADDRESS  0x21
#define REGISTER_VC12_HI_ADDRESS  0x22
#define REGISTER_VC12_LO_ADDRESS  0x23
#define REGISTER_VC13_HI_ADDRESS  0x24
#define REGISTER_VC13_LO_ADDRESS  0x25
#define REGISTER_VC14_HI_ADDRESS  0x26
#define REGISTER_VC14_LO_ADDRESS  0x27
#define REGISTER_VC15_HI_ADDRESS  0x28
#define REGISTER_VC15_LO_ADDRESS  0x29
#define REGISTER_BAT_HI_ADDRESS   0x2A
#define REGISTER_BAT_LO_ADDRESS   0x2B
#define REGISTER_TS1_HI_ADDRESS   0x2C
#define REGISTER_TS1_LO_ADDRESS   0x2D
#define REGISTER_TS2_HI_ADDRESS   0x2E
#define REGISTER_TS2_LO_ADDRESS   0x2F
#define REGISTER_TS3_HI_ADDRESS   0x30
#define REGISTER_TS3_LO_ADDRESS   0x31
#define REGISTER_ADCGAIN1_ADDRESS 0x50
#define REGISTER_ADCOFFSET_ADDRESS 0x51
#define REGISTER_ADCGAIN2_ADDRESS 0x59

#endif